# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='name')),
                ('website', models.URLField(blank=True, verbose_name='website')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DealerScraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('class_name', models.CharField(max_length=128, verbose_name='class name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.Dealer', verbose_name='dealer')),
            ],
            options={
                'abstract': False,
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DealerScraperReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('attempted', models.PositiveIntegerField(default=0, verbose_name='attempted')),
                ('processed', models.PositiveIntegerField(default=0, verbose_name='processed')),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.DealerScraper', verbose_name='scraper')),
            ],
            options={
                'abstract': False,
                'ordering': ['id'],
            },
        ),
    ]
