# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='name')),
                ('website', models.URLField(blank=True, verbose_name='website')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
