# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerscraperreport',
            name='manufacturers_created',
            field=models.PositiveIntegerField(default=0, verbose_name='manufacturers created'),
        ),
        migrations.AddField(
            model_name='dealerscraperreport',
            name='materials_created',
            field=models.PositiveIntegerField(default=0, verbose_name='materials created'),
        ),
    ]
