# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_auto_20170109_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealerscraper',
            options={'verbose_name_plural': 'Dealer Scrapers'},
        ),
        migrations.AlterModelOptions(
            name='dealerscraperreport',
            options={'verbose_name_plural': 'Dealer Scraper Reports'},
        ),
    ]
