# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_auto_20170115_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerscraperreport',
            name='attempted',
        ),
        migrations.RemoveField(
            model_name='dealerscraperreport',
            name='processed',
        ),
        migrations.AddField(
            model_name='dealerscraperreport',
            name='driver_product_listings_created',
            field=models.PositiveIntegerField(default=0, verbose_name='driver product listings created'),
        ),
        migrations.AddField(
            model_name='dealerscraperreport',
            name='driver_product_listings_updated',
            field=models.PositiveIntegerField(default=0, verbose_name='driver product listings updated'),
        ),
        migrations.AddField(
            model_name='dealerscraperreport',
            name='drivers_created',
            field=models.PositiveIntegerField(default=0, verbose_name='drivers created'),
        ),
        migrations.AddField(
            model_name='dealerscraperreport',
            name='errors',
            field=models.PositiveIntegerField(default=0, verbose_name='errors'),
        ),
    ]
