# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerScraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('file_path', models.CharField(max_length=128, validators=[utils.validators.validate_file_path], verbose_name='file path')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Dealer', verbose_name='dealer')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DealerScraperReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('attempted', models.PositiveIntegerField(default=0, verbose_name='attempted')),
                ('processed', models.PositiveIntegerField(default=0, verbose_name='processed')),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.DealerScraper', verbose_name='scraper')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
