# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 23:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('bl_product', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='BL Product (Tm)')),
                ('dc_resistance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Resistance (ohms)')),
                ('diaphragm_mass_including_airload', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Diaphragm Mass Inc. Airload (g)')),
                ('electromagnetic_q', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Electromagnetic Q')),
                ('frequency_response', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, verbose_name='Frequency Response (Hz)')),
                ('in_production', models.BooleanField(default=True, verbose_name='In Production')),
                ('max_power', models.IntegerField(blank=True, null=True, verbose_name='Max Power (Watts)')),
                ('mechanical_q', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Mechanical Q')),
                ('model', models.CharField(db_index=True, max_length=128, verbose_name='Model')),
                ('nominal_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nominal Diameter (Inches)')),
                ('nominal_impedance', models.IntegerField(blank=True, null=True, verbose_name='Nominal Impedance (Ohms)')),
                ('resonant_frequency', models.DecimalField(blank=True, decimal_places=2, help_text='Fs', max_digits=7, null=True, verbose_name='Resonant Frequency (Hertz)')),
                ('rms_power', models.IntegerField(blank=True, null=True, verbose_name='RMS power (Watts)')),
                ('sensitivity', models.DecimalField(blank=True, decimal_places=2, help_text='2.83V/1m', max_digits=5, null=True, verbose_name='Sensitivity (Decibels)')),
                ('voice_coil_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Voice Coil Diameter (Inches)')),
                ('voice_coil_inductance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Voice Coil Inductance (MilliHenries)')),
            ],
            options={
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='DriverGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'Driver Groups',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DriverProductListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('path', models.CharField(max_length=128, verbose_name='path')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.Dealer', verbose_name='dealer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_product_listings', to='drivers.Driver', verbose_name='driver')),
            ],
            options={
                'verbose_name_plural': 'Driver Product Listings',
                'ordering': ['id'],
            },
        ),
    ]
