# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivergroup',
            options={'ordering': ['id'], 'verbose_name_plural': 'Driver Groups'},
        ),
        migrations.AlterModelOptions(
            name='driverproductlisting',
            options={'ordering': ['id'], 'verbose_name_plural': 'Driver Product Listings'},
        ),
    ]
