# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('drivers', '0002_drivergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProductListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('path', models.CharField(max_length=128, verbose_name='path')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Dealer', verbose_name='dealer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver', verbose_name='driver')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
