# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_dc_resistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='voice_coil_inductance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Voice Coil Inductance (MilliHenries)'),
        ),
    ]
