# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20170116_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cone_surface_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Surface Area of Cone (cm**2)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='maximum_linear_excursion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Maximum Linear Excursion (mm)'),
        ),
    ]
