# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 06:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20170115_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='frequency_response',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, verbose_name='Frequency Response (Hz)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='voice_coil_diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Voice Coil Diameter (Inches)'),
        ),
    ]
