# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_voice_coil_inductance'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='mechanical_q',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Mechanical Q'),
        ),
    ]
