# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20170117_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='compliance_equivalent_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Compliance Equivalent Volume (ft**3)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='mechanical_compliance_of_suspension',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Mechanical Compliance of Suspension (mm/N)'),
        ),
    ]
