# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20161228_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='data_source',
        ),
    ]
