# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
        ('drivers', '0005_auto_20170118_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='cone_material',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='surround_material',
        ),
        migrations.AddField(
            model_name='driver',
            name='cone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_cone', to='manufacturing.Material', verbose_name='cone'),
        ),
        migrations.AddField(
            model_name='driver',
            name='surround',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_surround', to='manufacturing.Material', verbose_name='surround'),
        ),
        migrations.AddField(
            model_name='driver',
            name='voice_coil_former',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_voice_coil_former', to='manufacturing.Material', verbose_name='voice coil former'),
        ),
        migrations.AddField(
            model_name='driver',
            name='voice_coil_wire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_voice_coil_wire', to='manufacturing.Material', verbose_name='voice coil wire'),
        ),
    ]
