# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-16 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_auto_20170119_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverproductlisting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
    ]
