# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_auto_20170316_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='bl_product',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='BL Product (Tm)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='compliance_equivalent_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Compliance Equivalent Volume (ft**3)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cone_surface_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Surface Area of Cone (cm**2)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='dc_resistance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='DC Resistance (ohms)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='diaphragm_mass_including_airload',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Diaphragm Mass Inc. Airload (g)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='electromagnetic_q',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Electromagnetic Q'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='max_linear_excursion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Maximum Linear Excursion (mm)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='mechanical_compliance_of_suspension',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Mechanical Compliance of Suspension (mm/N)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='mechanical_q',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Mechanical Q'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='nominal_diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Nominal Diameter (Inches)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='sensitivity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='2.83V/1m', max_digits=7, null=True, verbose_name='Sensitivity (Decibels)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='voice_coil_diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Voice Coil Diameter (Inches)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='voice_coil_inductance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Voice Coil Inductance (MilliHenries)'),
        ),
    ]
